{
	"results": [
		{
			"id": "sha256:6743013c0bec3cacd7a756ed1eed58f264daef6fed944f5e22e581bfc89fe8d8",
			"name": "gcr.io-distroless-python3-debian11:latest",
			"distro": "Distroless (based on Debian GNU/Linux 11)",
			"distroRelease": "bullseye",
			"collections": [
				"All"
			],
			"packages": [
				{
					"type": "os",
					"name": "dash",
					"version": "0.5.11+git20200708+dd9ef66-5",
					"licenses": [
						"BSD-3-Clause"
					]
				},
				{
					"type": "os",
					"name": "netbase",
					"version": "6.3",
					"licenses": [
						"GPL-2"
					]
				},
				{
					"type": "os",
					"name": "tzdata",
					"version": "2021a-1+deb11u10"
				},
				{
					"type": "os",
					"name": "base-files",
					"version": "11.1+deb11u7",
					"licenses": [
						"GPL"
					]
				},
				{
					"type": "os",
					"name": "ncurses",
					"version": "6.2+20201114-2+deb11u1",
					"licenses": [
						"MIT/X11"
					]
				},
				{
					"type": "os",
					"name": "python3.9",
					"version": "3.9.2-1",
					"licenses": [
						"GPL-2"
					]
				},
				{
					"type": "os",
					"name": "readline",
					"version": "8.1-1",
					"licenses": [
						"GPL-3"
					]
				},
				{
					"type": "os",
					"name": "bzip2",
					"version": "1.0.8-4",
					"licenses": [
						"BSD-variant"
					]
				},
				{
					"type": "os",
					"name": "util-linux",
					"version": "2.36.1-8+deb11u1",
					"licenses": [
						"GPL-2+"
					]
				},
				{
					"type": "os",
					"name": "keyutils",
					"version": "1.6.1-2",
					"licenses": [
						"GPL-2+"
					]
				},
				{
					"type": "os",
					"name": "openssl",
					"version": "1.1.1n-0+deb11u5"
				},
				{
					"type": "os",
					"name": "libtirpc",
					"version": "1.3.1-1+deb11u1",
					"licenses": [
						"BSD-3-Clause"
					]
				},
				{
					"type": "os",
					"name": "python3-stdlib-extensions",
					"version": "3.9.2-1"
				},
				{
					"type": "os",
					"name": "libxcrypt",
					"version": "1:4.4.18-4"
				},
				{
					"type": "os",
					"name": "gcc-10",
					"version": "10.2.1-6"
				},
				{
					"type": "os",
					"name": "krb5",
					"version": "1.18.3-6+deb11u3",
					"licenses": [
						"GPL-2"
					]
				},
				{
					"type": "os",
					"name": "glibc",
					"version": "2.31-13+deb11u6",
					"licenses": [
						"LGPL-2.1"
					]
				},
				{
					"type": "os",
					"name": "xz-utils",
					"version": "5.2.5-2.1~deb11u1",
					"licenses": [
						"GPL-2+"
					]
				},
				{
					"type": "os",
					"name": "db5.3",
					"version": "5.3.28+dfsg1-0.8"
				},
				{
					"type": "os",
					"name": "e2fsprogs",
					"version": "1.46.2-2"
				},
				{
					"type": "os",
					"name": "libnsl",
					"version": "1.3.0-2",
					"licenses": [
						"LGPL-2.1+"
					]
				},
				{
					"type": "os",
					"name": "mpdecimal",
					"version": "2.5.1-1",
					"licenses": [
						"BSD"
					]
				},
				{
					"type": "os",
					"name": "sqlite3",
					"version": "3.34.1-3",
					"licenses": [
						"GPL-2+"
					]
				},
				{
					"type": "os",
					"name": "expat",
					"version": "2.2.10-2+deb11u5",
					"licenses": [
						"MIT"
					]
				},
				{
					"type": "os",
					"name": "zlib",
					"version": "1:1.2.11.dfsg-2+deb11u2"
				},
				{
					"type": "os",
					"name": "libffi",
					"version": "3.3-6",
					"licenses": [
						"GPL"
					]
				}
			],
			"applications": [
				{
					"name": "python",
					"version": "3.9.2",
					"path": "/usr/bin/python3.9"
				}
			],
			"compliances": [
				{
					"id": 41,
					"title": "(CIS_Docker_v1.5.0 - 4.1) Image should be created with a non-root user",
					"severity": "high",
					"description": "It is a good practice to run the container as a non-root user, if possible. Though user\nnamespace mapping is now available, if a user is already defined in the container image, the\ncontainer is run as that user by default and specific user namespace remapping is not\nrequired",
					"layerTime": "1970-01-01T00:00:00Z",
					"category": "Docker"
				}
			],
			"complianceDistribution": {
				"critical": 0,
				"high": 1,
				"medium": 0,
				"low": 0,
				"total": 1
			},
			"complianceScanPassed": true,
			"vulnerabilities": [
				{
					"id": "CVE-2023-4813",
					"status": "open",
					"cvss": 5.9,
					"vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"description": "A flaw was found in glibc. In an uncommon situation, the gaih_inet function may use memory that has been freed, resulting in an application crash. This issue is only exploitable when the getaddrinfo function is called and the hosts database in /etc/nsswitch.conf is configured with SUCCESS=continue or SUCCESS=merge.",
					"severity": "medium",
					"packageName": "glibc",
					"packageVersion": "2.31-13+deb11u6",
					"link": "https://security-tracker.debian.org/tracker/CVE-2023-4813",
					"riskFactors": [
						"Recent vulnerability",
						"Attack vector: network",
						"DoS - High",
						"Medium severity"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2023-09-12T22:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2023-40217",
					"status": "open",
					"cvss": 5.3,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
					"description": "An issue was discovered in Python before 3.8.18, 3.9.x before 3.9.18, 3.10.x before 3.10.13, and 3.11.x before 3.11.5. It primarily affects servers (such as HTTP servers) that use TLS client authentication. If a TLS server-side socket is created, receives data into the socket buffer, and then is closed quickly, there is a brief window where the SSLSocket instance will detect the socket as \\\"not connected\\\" and won\\'t initiate a handshake, but buffered data will still be readable from the socket buffer. This data will not be authenticated if the server-side TLS peer is expecting client certificate authentication, and is indistinguishable from valid TLS stream data. Data is limited in size to the amount that will fit in the buffer. (The TLS connection cannot directly be used for data exfiltration because the vulnerable code path requires that the connection be closed on initialization of the SSLSocket.)",
					"severity": "medium",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2023-40217",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network",
						"Medium severity",
						"Recent vulnerability"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2023-08-25T01:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2021-29921",
					"status": "open",
					"cvss": 9.8,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
					"description": "In Python before 3,9,5, the ipaddress library mishandles leading zero characters in the octets of an IP address string. This (in some situations) allows attackers to bypass access control that is based on IP addresses.",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2021-29921",
					"riskFactors": [
						"Attack vector: network",
						"DoS - High",
						"Attack complexity: low"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2021-05-06T13:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2019-8457",
					"status": "open",
					"cvss": 9.8,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
					"description": "SQLite3 from 3.6.0 to and including 3.27.2 is vulnerable to heap out-of-bound read in the rtreenode() function when handling invalid rtree tables.",
					"severity": "low",
					"packageName": "db5.3",
					"packageVersion": "5.3.28+dfsg1-0.8",
					"link": "https://security-tracker.debian.org/tracker/CVE-2019-8457",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network",
						"DoS - High"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2019-05-30T16:29:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2023-29491",
					"status": "open",
					"cvss": 7.8,
					"vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
					"description": "ncurses before 6.4 20230408, when used by a setuid application, allows local users to trigger security-relevant memory corruption via malformed data in a terminfo database file that is found in $HOME/.terminfo or reached via the TERMINFO or TERM environment variable.",
					"severity": "low",
					"packageName": "ncurses",
					"packageVersion": "6.2+20201114-2+deb11u1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2023-29491",
					"riskFactors": [
						"Attack complexity: low",
						"DoS - High",
						"Recent vulnerability"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2023-04-14T01:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2022-42919",
					"status": "open",
					"cvss": 7.8,
					"vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
					"description": "Python 3.9.x before 3.9.16 and 3.10.x before 3.10.9 on Linux allows local privilege escalation in a non-default configuration. The Python multiprocessing library, when used with the forkserver start method on Linux, allows pickles to be deserialized from any user in the same machine local network namespace, which in many system configurations means any user on the same machine. Pickles can execute arbitrary code. Thus, this allows for local user privilege escalation to the user that any forkserver process is running as. Setting multiprocessing.util.abstract_sockets_supported to False is a workaround. The forkserver start method for multiprocessing is not the default start method. This issue is Linux specific because only Linux supports abstract namespace sockets. CPython before 3.9 does not make use of Linux abstract namespace sockets by default. Support for users manually specifying an abstract namespace socket was added as a bugfix in 3.7.8 and 3.8.3, but users would need to make specific uncommon API calls in order to do that in CPython before 3.9.",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2022-42919",
					"riskFactors": [
						"Remote execution",
						"Attack complexity: low",
						"DoS - High"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2022-11-07T00:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2022-1304",
					"status": "open",
					"cvss": 7.8,
					"vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
					"description": "An out-of-bounds read/write vulnerability was found in e2fsprogs 1.46.5. This issue leads to a segmentation fault and possibly arbitrary code execution via a specially crafted filesystem.",
					"severity": "low",
					"packageName": "e2fsprogs",
					"packageVersion": "1.46.2-2",
					"link": "https://security-tracker.debian.org/tracker/CVE-2022-1304",
					"riskFactors": [
						"DoS - High",
						"Remote execution",
						"Attack complexity: low"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2022-04-14T21:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2015-20107",
					"status": "open",
					"cvss": 7.6,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:H/A:L",
					"description": "In Python (aka CPython) up to 3.10.8, the mailcap module does not add escape characters into commands discovered in the system mailcap file. This may allow attackers to inject shell commands into applications that call mailcap.findmatch with untrusted input (if they lack validation of user-provided filenames or arguments). The fix is also back-ported to 3.7, 3.8, 3.9",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2015-20107",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network",
						"DoS - Low"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2022-04-13T16:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2023-4806",
					"status": "open",
					"cvss": 7.5,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"description": "A flaw was found in glibc. In an extremely rare situation, the getaddrinfo function may access memory that has been freed, resulting in an application crash. This issue is only exploitable when a NSS module implements only the _nss_*_gethostbyname2_r and _nss_*_getcanonname_r hooks without implementing the _nss_*_gethostbyname3_r hook. The resolved name should return a large number of IPv6 and IPv4, and the call to the getaddrinfo function should have the AF_INET6 address family with AI_CANONNAME, AI_ALL and AI_V4MAPPED as flags.",
					"severity": "low",
					"packageName": "glibc",
					"packageVersion": "2.31-13+deb11u6",
					"link": "https://security-tracker.debian.org/tracker/CVE-2023-4806",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network",
						"DoS - High",
						"Recent vulnerability"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2023-09-18T17:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2023-24329",
					"status": "open",
					"cvss": 7.5,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
					"description": "An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2023-24329",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2023-02-17T15:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2022-45061",
					"status": "open",
					"cvss": 7.5,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"description": "An issue was discovered in Python before 3.11.1. An unnecessary quadratic algorithm exists in one path when processing some inputs to the IDNA (RFC 3490) decoder, such that a crafted, unreasonably long name being presented to the decoder could lead to a CPU denial of service. Hostnames are often supplied by remote servers that could be controlled by a malicious actor; in such a scenario, they could trigger excessive CPU consumption on the client attempting to make use of an attacker-supplied supposed hostname. For example, the attack payload could be placed in the Location header of an HTTP response with status code 302. A fix is planned in 3.11.1, 3.10.9, 3.9.16, 3.8.16, and 3.7.16.",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2022-45061",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network",
						"DoS - High"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2022-11-09T07:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2022-0391",
					"status": "open",
					"cvss": 7.5,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
					"description": "A flaw was found in Python, specifically within the urllib.parse module. This module helps break Uniform Resource Locator (URL) strings into components. The issue involves how the urlparse method does not sanitize input and allows characters like \\'\\r\\' and \\'\\n\\' in the URL path. This flaw allows an attacker to input a crafted URL, leading to injection attacks. This flaw affects Python versions prior to 3.10.0b1, 3.9.5, 3.8.11, 3.7.11 and 3.6.14.",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2022-0391",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2022-02-09T23:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2021-3737",
					"status": "open",
					"cvss": 7.5,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"description": "A flaw was found in python. An improperly handled HTTP response in the HTTP client code of python may allow a remote attacker, who controls the HTTP server, to make the client script enter an infinite loop, consuming CPU time. The highest threat from this vulnerability is to system availability.",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2021-3737",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network",
						"DoS - High"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2022-03-04T19:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2021-31239",
					"status": "open",
					"cvss": 7.5,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"description": "An issue found in SQLite SQLite3 v.3.35.4 that allows a remote attacker to cause a denial of service via the appendvfs.c function.",
					"severity": "low",
					"packageName": "sqlite3",
					"packageVersion": "3.34.1-3",
					"link": "https://security-tracker.debian.org/tracker/CVE-2021-31239",
					"riskFactors": [
						"Exploit exists - POC",
						"Recent vulnerability",
						"Attack complexity: low",
						"Attack vector: network",
						"DoS - High"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2023-05-09T02:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2020-10735",
					"status": "open",
					"cvss": 7.5,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"description": "A flaw was found in python. In algorithms with quadratic time complexity using non-binary bases, when using int(\\\"text\\\"), a system could take 50ms to parse an int string with 100,000 digits and 5s for 1,000,000 digits (float, decimal, int.from_bytes(), and int() for binary bases 2, 4, 8, 16, and 32 are not affected). The highest threat from this vulnerability is to system availability.",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2020-10735",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network",
						"DoS - High"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2022-09-09T14:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2023-36054",
					"status": "open",
					"cvss": 6.5,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
					"description": "lib/kadm5/kadm_rpc_xdr.c in MIT Kerberos 5 (aka krb5) before 1.20.2 and 1.21.x before 1.21.1 frees an uninitialized pointer. A remote authenticated user can trigger a kadmind crash. This occurs because _xdr_kadm5_principal_ent_rec does not validate the relationship between n_key_data and the key_data array count.",
					"severity": "low",
					"packageName": "krb5",
					"packageVersion": "1.18.3-6+deb11u3",
					"link": "https://security-tracker.debian.org/tracker/CVE-2023-36054",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network",
						"DoS - High",
						"Recent vulnerability"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2023-08-07T19:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2021-3733",
					"status": "open",
					"cvss": 6.5,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
					"description": "There\\'s a flaw in urllib\\'s AbstractBasicAuthHandler class. An attacker who controls a malicious HTTP server that an HTTP client (such as web browser) connects to, could trigger a Regular Expression Denial of Service (ReDOS) during an authentication request with a specially crafted payload that is sent by the server to the client. The greatest threat that this flaw poses is to application availability.",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2021-3733",
					"riskFactors": [
						"Attack vector: network",
						"DoS - High",
						"Attack complexity: low"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2022-03-10T17:42:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2021-3426",
					"status": "open",
					"cvss": 5.7,
					"vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
					"description": "There\\'s a flaw in Python 3\\'s pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2021-3426",
					"riskFactors": [
						"Attack complexity: low"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2021-05-20T13:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2023-3817",
					"status": "open",
					"cvss": 5.3,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
					"description": "Issue summary: Checking excessively long DH keys or parameters may be very slow.  Impact summary: Applications that use the functions DH_check(), DH_check_ex() or EVP_PKEY_param_check() to check a DH key or DH parameters may experience long delays. Where the key or parameters that are being checked have been obtained from an untrusted source this may lead to a Denial of Service.  The function DH_check() performs various checks on DH parameters. After fixing CVE-2023-3446 it was discovered that a large q parameter value can also trigger an overly long computation during some of these checks. A correct q value, if present, cannot be larger than the modulus p parameter, thus it is unnecessary to perform these checks if q is larger than p.  An application that calls DH_check() and supplies a key or parameters obtained from an untrusted source could be vulnerable to a Denial of Service attack.  The function DH_check() is itself called by a number of other OpenSSL functions. An application calling any of those other functions may similarly be affected. The other functions affected by this are DH_check_ex() and EVP_PKEY_param_check().  Also vulnerable are the OpenSSL dhparam and pkeyparam command line applications when using the \\\"-check\\\" option.  The OpenSSL SSL/TLS implementation is not affected by this issue.  The OpenSSL 3.0 and 3.1 FIPS providers are not affected by this issue.",
					"severity": "low",
					"packageName": "openssl",
					"packageVersion": "1.1.1n-0+deb11u5",
					"link": "https://security-tracker.debian.org/tracker/CVE-2023-3817",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network",
						"DoS - Low",
						"Recent vulnerability"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2023-07-31T16:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2023-3446",
					"status": "open",
					"cvss": 5.3,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
					"description": "Issue summary: Checking excessively long DH keys or parameters may be very slow.  Impact summary: Applications that use the functions DH_check(), DH_check_ex() or EVP_PKEY_param_check() to check a DH key or DH parameters may experience long delays. Where the key or parameters that are being checked have been obtained from an untrusted source this may lead to a Denial of Service.  The function DH_check() performs various checks on DH parameters. One of those checks confirms that the modulus (\\'p\\' parameter) is not too large. Trying to use a very large modulus is slow and OpenSSL will not normally use a modulus which is over 10,000 bits in length.  However the DH_check() function checks numerous aspects of the key or parameters that have been supplied. Some of those checks use the supplied modulus value even if it has already been found to be too large.  An application that calls DH_check() and supplies a key or parameters obtained from an untrusted source could be vulernable to a Denial of Service attack.  The function DH_check() is itself called by a number of other OpenSSL functions. An application calling any of those other functions may similarly be affected. The other functions affected by this are DH_check_ex() and EVP_PKEY_param_check().  Also vulnerable are the OpenSSL dhparam and pkeyparam command line applications when using the \\'-check\\' option.  The OpenSSL SSL/TLS imp",
					"severity": "low",
					"packageName": "openssl",
					"packageVersion": "1.1.1n-0+deb11u5",
					"link": "https://security-tracker.debian.org/tracker/CVE-2023-3446",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network",
						"DoS - Low",
						"Recent vulnerability"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2023-07-19T12:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2023-27043",
					"status": "open",
					"cvss": 5.3,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
					"description": "The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2023-27043",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network",
						"Recent vulnerability"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2023-04-19T00:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2021-4189",
					"status": "open",
					"cvss": 5.3,
					"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
					"description": "A flaw was found in Python, specifically in the FTP (File Transfer Protocol) client library in PASV (passive) mode. The issue is how the FTP client trusts the host from the PASV response by default. This flaw allows an attacker to set up a malicious FTP server that can trick FTP clients into connecting back to a given IP address and port. This vulnerability could lead to FTP client scanning ports, which otherwise would not have been possible.",
					"severity": "low",
					"packageName": "python3.9",
					"packageVersion": "3.9.2-1",
					"link": "https://security-tracker.debian.org/tracker/CVE-2021-4189",
					"riskFactors": [
						"Attack complexity: low",
						"Attack vector: network"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2022-08-24T16:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				},
				{
					"id": "CVE-2023-4039",
					"status": "open",
					"cvss": 4.8,
					"vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N",
					"description": "  A failure in the -fstack-protector feature in GCC-based toolchains  that target AArch64 allows an attacker to exploit an existing buffer  overflow in dynamically-sized local variables in your application  without this being detected. This stack-protector failure only applies  to C99-style dynamically-sized local variables or those created using  alloca(). The stack-protector operates as intended for statically-sized  local variables.  The default behavior when the stack-protector  detects an overflow is to terminate your application, resulting in  controlled loss of availability. An attacker who can exploit a buffer  overflow without triggering the stack-protector might be able to change  program flow control to cause an uncontrolled loss of availability or to  go further and affect confidentiality or integrity.      ",
					"severity": "low",
					"packageName": "gcc-10",
					"packageVersion": "10.2.1-6",
					"link": "https://security-tracker.debian.org/tracker/CVE-2023-4039",
					"riskFactors": [
						"Attack vector: network",
						"Recent vulnerability"
					],
					"impactedVersions": [
						"*"
					],
					"publishedDate": "2023-09-13T09:15:00Z",
					"discoveredDate": "2023-09-23T10:58:17Z",
					"layerTime": "1970-01-01T00:00:00Z"
				}
			],
			"vulnerabilityDistribution": {
				"critical": 0,
				"high": 0,
				"medium": 2,
				"low": 21,
				"total": 23
			},
			"vulnerabilityScanPassed": true,
			"history": [
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z"
				},
				{
					"created": "0001-01-01T00:00:00Z",
					"instruction": "CMD [\"/bin/sh\" \"-c\" \"echo \\\"Hello world\\\"\"]"
				}
			],
			"scanTime": "2023-09-23T10:58:19.041974328Z"
		}
	],
	"consoleURL": "https://app.eu.prismacloud.io/compute?computeState=/monitor/vulnerabilities/images/ci?search=sha256%3A6743013c0bec3cacd7a756ed1eed58f264daef6fed944f5e22e581bfc89fe8d8"
}